name: Generate Commit History

on: push

jobs:
  generate-history:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # This is important to fetch all commits

    - name: Generate commit history
      run: |
        echo "Commit History" > COMMIT_HISTORY.md
        echo "---------------" >> COMMIT_HISTORY.md
        git log --pretty=format:"%h - %s (%an, %ar)" >> COMMIT_HISTORY.md

    - name: Commit and push if changed
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add COMMIT_HISTORY.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update COMMIT_HISTORY.md"
        git push
